In [41]:
from sklearn import preprocessing
from sklearn.feature_selection import SelectPercentile
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import f_classif
from sklearn.preprocessing import StandardScaler

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline

In [42]:
csidf = pd.read_excel("subcarriers_amp_pos_pot.xlsx", sheet_name="subcarriers_amp_pos_pot")
csidf.drop("Unnamed: 0", axis=1, inplace=True)
csidf.head()

device local  x  y  P_MW_LLTF  P_MW_HTLTF  P_DBM_LLTF  P_DBM_HTLTF  \
0    DIR    A1  1  3         68        1763   18.326305    32.462711   
1    DIR    A1  1  3         91        2902   19.625982    34.627993   
2    DIR    A1  1  3         79        1819   19.009755    32.599737   
3    DIR    A1  1  3         82        2482   19.157725    33.949590   
4    DIR    A1  1  3         43         736   16.433430    28.670187   

   LLTF_-32  LLTF_-31  ...   HTLTF_22   HTLTF_23   HTLTF_24   HTLTF_25  \
0         0         0  ...  22.090722  19.000000  17.029386  15.132746   
1         0         0  ...  24.083189  22.203603  19.416488  17.720045   
2         0         0  ...  21.023796  18.110770  17.464249  15.811388   
3         0         0  ...  21.954498  19.416488  17.029386  15.556349   
4         0         0  ...  20.000000  17.492856  15.231546  13.601471   

    HTLTF_26   HTLTF_27   HTLTF_28  HTLTF_29  HTLTF_30  HTLTF_31  
0  14.560220  12.806248  13.601471  2.236068  0.000000  1.414214  
1  17.464249  15.620499  15.000000  3.605551  2.236068  0.000000  
2  14.317821  13.453624  12.806248  2.236068  1.000000  1.414214  
3  15.000000  12.649111  12.041595  2.000000  0.000000  1.000000  
4  13.152946  13.038405  12.369317  2.236068  1.000000  1.414214  

[5 rows x 134 columns]

In [43]:
#Separando os dados de treino e teste igualmente em cada posição e direção - APENAS LLTF
colunas = csidf.columns[8:134]
aux = 0
#X_train, X_test, y_train, y_test
for k in csidf["local"].unique():
#     datalltf = csidf[csidf["local"]==k]
    for j in csidf["device"].unique():
#         datalltf = datalltf[datalltf["device"]==j]
        data_y = csidf[(csidf["local"]==k) & (csidf["device"]==j)].copy()
        datalltf= data_y[colunas]
        if aux==0:
            X_train, X_test, y_train, y_test = train_test_split(datalltf,data_y["local"],test_size=0.2)
            aux=aux+1
        else:
            X_train_aux, X_test_aux, y_train_aux, y_test_aux = train_test_split(datalltf,data_y["local"],test_size=0.2)
            X_train = X_train.append(X_train_aux)
            X_test = X_test.append(X_test_aux)
            y_train = y_train.append(y_train_aux)
            y_test = y_test.append(y_test_aux)

In [44]:
X = csidf[csidf.columns[8:134]]
scaler = StandardScaler()
scaler = scaler.fit(X_train)
X_bef = X_train
X_train = pd.DataFrame(scaler.transform(X_train))
selector = SelectPercentile(f_classif, percentile=89)
X_std = X_train
X_train = pd.DataFrame(selector.fit_transform(X_train, y_train))
#X_train = X_train[cols].reset_index(drop=True)
#X_train.columns = range(X_train.shape[1])

#X_test = X_test[cols].reset_index(drop=True)
#X_test.columns = range(X_test.shape[1])
X_test = pd.DataFrame(scaler.transform(X_test))

C:\Users\iande\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\iande\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """
C:\Users\iande\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:114: UserWarning: Features [ 0  1  2  3  4 58 59 60 61] are constant.
  UserWarning)
C:\Users\iande\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
C:\Users\iande\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  


In [45]:
X_train.shape

(1536, 112)

In [46]:
cols = selector.get_support(1)
cols

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123], dtype=int64)

In [47]:
selCount = selector.get_support(1).shape[0]
selCount

112

In [48]:
df_scores = pd.DataFrame()
df_scores['Scores'] = selector.scores_
df_scores['Subport'] = datalltf.columns

In [49]:
#TABELA POR ORDEM DE ID

teste = df_scores.sort_values(['Scores'], ascending=False).round(1)[0:selCount]
teste = teste.reset_index(drop=False).sort_values(['index'], ascending=True)
teste = teste.reset_index(drop=True)
teste = teste.reset_index(drop=True)#teste['id'] = teste['level_0']
#teste = teste.drop(['index','Scores','Organização'], axis=1)
teste
#testeFile = teste.drop(['index','Scores','Organização'], axis=1)
#testeFile.to_csv('mac_phygitall_100619', sep='\t')
#teste.sort_values(['index'], ascending=False).reset_index(drop=False).sort_values(['level_0'], ascending=False)

index  Scores   Subport
0        5    21.7  LLTF_-27
1        6    28.6  LLTF_-26
2        7    29.8  LLTF_-25
3        8    30.2  LLTF_-24
4        9    29.7  LLTF_-23
5       10    29.5  LLTF_-22
6       11    28.7  LLTF_-21
7       12    27.5  LLTF_-20
8       13    25.4  LLTF_-19
9       14    24.5  LLTF_-18
10      15    24.6  LLTF_-17
11      16    24.4  LLTF_-16
12      17    23.4  LLTF_-15
13      18    22.6  LLTF_-14
14      19    21.9  LLTF_-13
15      20    24.6  LLTF_-12
16      21    25.8  LLTF_-11
17      22    25.4  LLTF_-10
18      23    27.4   LLTF_-9
19      24    29.7   LLTF_-8
20      25    31.3   LLTF_-7
21      26    35.1   LLTF_-6
22      27    38.7   LLTF_-5
23      28    41.9   LLTF_-4
24      29    44.0   LLTF_-3
25      30    46.4   LLTF_-2
26      31    46.7   LLTF_-1
27      32    55.6    LLTF_2
28      33    58.5    LLTF_3
29      34    57.1    LLTF_4
..     ...     ...       ...
82      93    31.4  HTLTF_-1
83      94    27.0   HTLTF_0
84      95    30.1   HTLTF_1
85      96    31.5   HTLTF_2
86      97    31.0   HTLTF_3
87      98    30.8   HTLTF_4
88      99    30.1   HTLTF_5
89     100    30.2   HTLTF_6
90     101    29.7   HTLTF_7
91     102    28.7   HTLTF_8
92     103    26.9   HTLTF_9
93     104    25.3  HTLTF_10
94     105    22.6  HTLTF_11
95     106    20.2  HTLTF_12
96     107    17.8  HTLTF_13
97     108    15.8  HTLTF_14
98     109    14.0  HTLTF_15
99     110    12.5  HTLTF_16
100    111    11.7  HTLTF_17
101    113    11.4  HTLTF_19
102    114    11.6  HTLTF_20
103    115    11.9  HTLTF_21
104    116    12.3  HTLTF_22
105    117    13.0  HTLTF_23
106    118    13.8  HTLTF_24
107    119    14.4  HTLTF_25
108    120    15.0  HTLTF_26
109    121    15.3  HTLTF_27
110    122    15.5  HTLTF_28
111    123    13.1  HTLTF_29

[112 rows x 3 columns]

In [50]:
#TABELA POR ORDEM DE SCORE
teste = df_scores.sort_values(['Scores'], ascending=False).round(1)
teste

Scores    Subport
33     58.5     LLTF_3
34     57.1     LLTF_4
32     55.6     LLTF_2
36     54.2     LLTF_6
35     53.8     LLTF_5
37     50.9     LLTF_7
38     48.6     LLTF_8
31     46.7    LLTF_-1
30     46.4    LLTF_-2
39     45.5     LLTF_9
29     44.0    LLTF_-3
40     42.1    LLTF_10
28     41.9    LLTF_-4
27     38.7    LLTF_-5
41     38.6    LLTF_11
42     35.3    LLTF_12
26     35.1    LLTF_-6
43     31.8    LLTF_13
96     31.5    HTLTF_2
93     31.4   HTLTF_-1
92     31.3   HTLTF_-2
25     31.3    LLTF_-7
97     31.0    HTLTF_3
98     30.8    HTLTF_4
91     30.8   HTLTF_-3
90     30.5   HTLTF_-4
8      30.2   LLTF_-24
100    30.2    HTLTF_6
95     30.1    HTLTF_1
99     30.1    HTLTF_5
..      ...        ...
108    15.8   HTLTF_14
122    15.5   HTLTF_28
121    15.3   HTLTF_27
64     15.1  HTLTF_-30
120    15.0   HTLTF_26
119    14.4   HTLTF_25
109    14.0   HTLTF_15
118    13.8   HTLTF_24
123    13.1   HTLTF_29
117    13.0   HTLTF_23
110    12.5   HTLTF_16
116    12.3   HTLTF_22
115    11.9   HTLTF_21
111    11.7   HTLTF_17
114    11.6   HTLTF_20
113    11.4   HTLTF_19
112    11.3   HTLTF_18
124     7.4   HTLTF_30
62      4.5  HTLTF_-32
63      0.8  HTLTF_-31
125     0.6   HTLTF_31
0       NaN   LLTF_-32
1       NaN   LLTF_-31
2       NaN   LLTF_-30
3       NaN   LLTF_-29
4       NaN   LLTF_-28
58      NaN    LLTF_28
59      NaN    LLTF_29
60      NaN    LLTF_30
61      NaN    LLTF_31

[126 rows x 2 columns]

In [63]:
# 33	58.5	LLTF_3
# 34	57.1	LLTF_4
# 32	55.6	LLTF_2
# 36	54.2	LLTF_6
# 35	53.8	LLTF_5
# 37	50.9	LLTF_7
# 38	48.6	LLTF_8
# 31	46.7	LLTF_-1
# 30	46.4	LLTF_-2
# 39	45.5	LLTF_9
# 29	44.0	LLTF_-3
# 40	42.1	LLTF_10
# 28	41.9	LLTF_-4
csidf[["LLTF_3","LLTF_4","LLTF_2","LLTF_6","LLTF_5","LLTF_7","LLTF_8","LLTF_-1","LLTF_-2","LLTF_9","LLTF_-3","LLTF_10","LLTF_-4"]]

LLTF_3     LLTF_4     LLTF_2     LLTF_6     LLTF_5     LLTF_7  \
0     24.000000  22.000000  25.000000  20.099751  21.023796  19.235384   
1     24.331050  24.331050  25.495098  21.095023  22.203603  20.024984   
2     24.515301  23.345235  25.495098  20.099751  21.213203  19.026298   
3     23.430749  22.803509  24.839485  20.248457  21.400935  19.723083   
4     20.591260  19.235384  21.470911  16.643317  18.357560  16.401219   
5     26.907248  26.172505  27.658633  23.345235  24.758837  22.022716   
6     24.041631  22.803509  25.000000  20.396078  21.587033  19.235384   
7     22.360680  21.377558  23.537205  19.104973  20.223748  18.027756   
8     23.853721  23.323808  24.413111  20.591260  21.954498  18.788294   
9     25.059928  23.706539  25.942244  20.808652  21.954498  20.000000   
10    26.925824  26.925824  27.294688  25.612497  25.806976  24.083189   
11    22.561028  22.360680  23.769729  20.099751  21.213203  20.024984   
12    23.853721  23.600847  24.698178  22.022716  22.803509  21.931712   
13    22.561028  22.360680  23.769729  21.095023  22.203603  20.000000   
14    23.021729  22.472205  23.600847  21.470911  21.954498  20.615528   
15    21.633308  20.591260  21.633308  18.384776  20.124612  18.973666   
16    24.698178  23.409400  25.632011  20.880613  22.135944  19.646883   
17    25.059928  23.706539  25.495098  21.633308  22.472205  20.000000   
18    24.351591  22.472205  25.000000  20.615528  21.540659  19.235384   
19    23.409400  22.472205  23.769729  18.973666  21.189620  18.681542   
20    24.166092  21.931712  24.596748  20.248457  20.615528  18.973666   
21    25.019992  24.020824  26.019224  21.377558  23.086793  20.615528   
22    24.186773  22.825424  24.186773  20.248457  21.931712  19.924859   
23    25.709920  24.738634  26.683328  21.189620  23.086793  20.615528   
24    24.041631  23.086793  24.738634  20.248457  22.135944  19.697716   
25    23.086793  21.840330  24.351591  19.235384  20.396078  18.248288   
26    23.323808  22.472205  24.186773  21.400935  22.203603  19.849433   
27    21.587033  20.396078  22.803509  19.104973  20.223748  18.027756   
28    26.019224  24.000000  27.073973  21.023796  23.021729  20.099751   
29    26.172505  24.758837  26.907248  22.671568  23.345235  20.615528   
...         ...        ...        ...        ...        ...        ...   
1890  27.586228  26.870058  29.068884  23.430749  24.758837  22.803509   
1891  26.627054  25.238859  28.017851  22.825424  24.698178  21.931712   
1892  26.019224  25.079872  27.018512  22.360680  23.086793  21.587033   
1893  26.683328  25.709920  27.459060  23.086793  23.769729  21.540659   
1894  27.000000  25.019992  28.017851  23.194827  24.083189  21.377558   
1895  26.683328  25.709920  27.459060  23.086793  24.738634  21.540659   
1896  27.073973  26.076810  28.017851  23.345235  25.179357  22.561028   
1897  24.083189  23.086793  26.019224  21.377558  22.203603  19.646883   
1898  29.068884  27.313001  30.413813  24.351591  26.000000  22.803509   
1899  24.041631  23.345235  24.758837  21.400935  22.671568  20.248457   
1900  26.172505  25.179357  27.294688  23.000000  24.020824  22.022716   
1901  27.018512  26.248809  27.802878  22.627417  24.758837  22.022716   
1902  27.658633  26.248809  28.425341  24.041631  25.495098  22.671568   
1903  24.041631  23.345235  25.455844  20.000000  22.022716  19.416488   
1904  26.000000  25.000000  27.018512  22.090722  24.020824  21.213203   
1905  26.248809  25.495098  27.018512  22.671568  24.041631  20.615528   
1906  26.683328  25.961510  28.635642  23.409400  24.351591  21.931712   
1907  28.425341  27.018512  30.479501  24.413111  26.400758  23.323808   
1908  26.248809  25.612497  28.319605  22.472205  23.600847  21.954498   
1909  26.172505  25.079872  27.294688  23.000000  24.020824  21.023796   
1910  26.925824  26.076810  27.784888  23.600847  24.413111  22.671568   
1911  30.066593  29.017236  30.149627  26.019224  28.000000  25.179357   
1912  27.7848

In [64]:
#Separando os dados de treino e teste igualmente em cada posição e direção - APENAS LLTF
colunas = ["LLTF_3","LLTF_4","LLTF_2","LLTF_6","LLTF_5","LLTF_7","LLTF_8","LLTF_-1","LLTF_-2","LLTF_9","LLTF_-3","LLTF_10","LLTF_-4"]
aux = 0
#X_train, X_test, y_train, y_test
for k in csidf["local"].unique():
#     datalltf = csidf[csidf["local"]==k]
    for j in csidf["device"].unique():
#         datalltf = datalltf[datalltf["device"]==j]
        data_y = csidf[(csidf["local"]==k) & (csidf["device"]==j)].copy()
        datalltf= data_y[colunas]
        if aux==0:
            X_train, X_test, y_train, y_test = train_test_split(datalltf,data_y["local"],test_size=0.2)
            aux=aux+1
        else:
            X_train_aux, X_test_aux, y_train_aux, y_test_aux = train_test_split(datalltf,data_y["local"],test_size=0.2)
            X_train = X_train.append(X_train_aux)
            X_test = X_test.append(X_test_aux)
            y_train = y_train.append(y_train_aux)
            y_test = y_test.append(y_test_aux)

LLTF_3     LLTF_4     LLTF_2     LLTF_6     LLTF_5     LLTF_7  \
37    23.259407  22.360680  24.596748  19.723083  21.470911  18.867962   
33    24.515301  23.537205  25.495098  20.880613  22.803509  20.248457   
19    23.409400  22.472205  23.769729  18.973666  21.189620  18.681542   
13    22.561028  22.360680  23.769729  21.095023  22.203603  20.000000   
38    26.172505  25.079872  27.166155  22.022716  23.086793  21.000000   
11    22.561028  22.360680  23.769729  20.099751  21.213203  20.024984   
12    23.853721  23.600847  24.698178  22.022716  22.803509  21.931712   
39    23.021729  21.633308  24.207437  19.235384  21.095023  18.384776   
8     23.853721  23.323808  24.413111  20.591260  21.954498  18.788294   
26    23.323808  22.472205  24.186773  21.400935  22.203603  19.849433   
31    24.698178  22.847319  25.298221  20.124612  21.931712  19.235384   
27    21.587033  20.396078  22.803509  19.104973  20.223748  18.027756   
0     24.000000  22.000000  25.000000  20.099751  21.023796  19.235384   
18    24.351591  22.472205  25.000000  20.615528  21.540659  19.235384   
24    24.041631  23.086793  24.738634  20.248457  22.135944  19.697716   
21    25.019992  24.020824  26.019224  21.377558  23.086793  20.615528   
6     24.041631  22.803509  25.000000  20.396078  21.587033  19.235384   
7     22.360680  21.377558  23.537205  19.104973  20.223748  18.027756   
16    24.698178  23.409400  25.632011  20.880613  22.135944  19.646883   
14    23.021729  22.472205  23.600847  21.470911  21.954498  20.615528   
15    21.633308  20.591260  21.633308  18.384776  20.124612  18.973666   
4     20.591260  19.235384  21.470911  16.643317  18.357560  16.401219   
36    25.059928  23.706539  26.419690  21.023796  22.360680  19.313208   
17    25.059928  23.706539  25.495098  21.633308  22.472205  20.000000   
35    22.472205  21.189620  23.409400  19.646883  19.924859  18.248288   
5     26.907248  26.172505  27.658633  23.345235  24.758837  22.022716   
9     25.059928  23.706539  25.942244  20.808652  21.954498  20.000000   
20    24.166092  21.931712  24.596748  20.248457  20.615528  18.973666   
1     24.331050  24.331050  25.495098  21.095023  22.203603  20.024984   
25    23.086793  21.840330  24.351591  19.235384  20.396078  18.248288   
...         ...        ...        ...        ...        ...        ...   
1906  26.683328  25.961510  28.635642  23.409400  24.351591  21.931712   
1890  27.586228  26.870058  29.068884  23.430749  24.758837  22.803509   
1880  28.600699  26.400758  29.410882  24.083189  25.612497  22.627417   
1913  30.870698  28.635642  31.304952  25.632011  26.925824  25.000000   
1881  30.594117  29.614186  31.400637  25.961510  27.658633  25.000000   
1891  26.627054  25.238859  28.017851  22.825424  24.698178  21.931712   
1912  27.784888  26.419690  29.154759  24.166092  25.495098  22.472205   
1918  26.570661  25.632011  27.202941  23.259407  24.698178  21.954498   
1899  24.041631  23.345235  24.758837  21.400935  22.671568  20.248457   
1904  26.000000  25.000000  27.018512  22.090722  24.020824  21.213203   
1882  26.925824  25.553865  28.301943  22.847319  23.706539  21.540659   
1888  27.294688  26.172505  28.442925  23.021729  24.083189  22.000000   
1914  24.738634  24.515301  25.961510  22.203603  23.345235  21.023796   
1893  26.683328  25.709920  27.459060  23.086793  23.769729  21.540659   
1887  26.305893  25.179357  27.294688  23.021729  24.083189  22.000000   
1894  27.000000  25.019992  28.017851  23.194827  24.083189  21.377558   
1907  28.425341  27.018512  30.479501  24.413111  26.400758  23.323808   
1915  28.160256  26.248809  29.120440  24.166092  24.698178  22.360680   
1903  24.041631  23.345235  25.455844  20.000000  22.022716  19.416488   
1917  27.073973  26.019224  28.160256  24.020824  25.000000  22.203603   
1898  29.068884  27.313001  30.413813  24.351591  26.000000  22.803509   
1901  27.018512  26.248809  27.802878  22.627417  24.758837  22.022716   
1884  26.0000

In [67]:
#### Usando SVC (Support Vector Classifier)
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)
#### PREDICOES SVC #####
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print("\n")
print(classification_report(y_test,predictions))

[[11  2  1  1  0  2  4  0  2  2  2  5]
 [ 3 10  1  0  2  2  0  1  4  6  0  3]
 [ 6  1 12  3  1  2  0  0  2  2  0  3]
 [ 2  2  2 13  2  0  4  0  2  1  2  2]
 [ 4  1  0  3  5  3  0  3  1  6  5  1]
 [ 4  1  1  0  2 18  0  0  3  1  2  0]
 [ 2  0  2  5  2  3 16  1  0  0  0  1]
 [ 1  0  4  2  1  7  2  7  3  0  4  1]
 [ 0  0  1  0  1  2  2  1 23  1  0  1]
 [ 0  2  2  4  4  2  0  3  3 11  0  1]
 [ 8  0  2  1  1  0  4  3  1  3  8  1]
 [ 4  0  0  2  1  1  0  0  0  1  1 22]]


              precision    recall  f1-score   support

          A1       0.24      0.34      0.29        32
          A2       0.53      0.31      0.39        32
          A3       0.43      0.38      0.40        32
          B1       0.38      0.41      0.39        32
          B2       0.23      0.16      0.19        32
          B3       0.43      0.56      0.49        32
          D1       0.50      0.50      0.50        32
          D2       0.37      0.22      0.27        32
          D3       0.52      0.72      0.6

C:\Users\iande\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [68]:
#Gridsearch#
# param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']}
# param_grid=dict(kernel=k, C=c, gamma=g)
param_grid = {'C': [0.1,1, 10,25,50,75,100,500, 1000], 'gamma': [1,0.8,0.6,0.5,0.3,0.2,0.1,0.05,0.01,0.001,0.0001], 'kernel': ['rbf', 'linear','poly','sigmoid']}
print(param_grid)

{'C': [0.1, 1, 10, 25, 50, 75, 100, 500, 1000], 'gamma': [1, 0.8, 0.6, 0.5, 0.3, 0.2, 0.1, 0.05, 0.01, 0.001, 0.0001], 'kernel': ['rbf', 'linear', 'poly', 'sigmoid']}


In [69]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [ ]:
# Talvez demore um pouco
grid.fit(X_train,y_train)

C:\Users\iande\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


Fitting 3 folds for each of 396 candidates, totalling 1188 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.1182170542635659, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.11434108527131782, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.10317460317460317, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.2s remaining:    0.0s


[CV]  C=0.1, gamma=1, kernel=linear, score=0.18604651162790697, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV]  C=0.1, gamma=1, kernel=linear, score=0.17829457364341086, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV]  C=0.1, gamma=1, kernel=linear, score=0.1746031746031746, total=   0.0s
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV]  C=0.1, gamma=1, kernel=poly, score=0.20736434108527133, total=61.5min
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV]  C=0.1, gamma=1, kernel=poly, score=0.2364341085271318, total=59.6min
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV]  C=0.1, gamma=1, kernel=poly, score=0.2003968253968254, total=61.2min
[CV] C=0.1, gamma=1, kernel=sigmoid ..................................
[CV]  C=0.1, gamma=1, kernel=sigmoid, score=0.08333333333333333, total=   0.0s
[CV] C=0.1, gamma=1, kernel=sigmoid 

In [ ]:
grid.best_params_

In [ ]:
grid.best_estimator_

In [ ]:
grid_predictions = grid.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,grid_predictions))

In [ ]:
print(classification_report(y_test,grid_predictions))